import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio de Nicolas Soto",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico']
  },
  openGraph: {
    url: "https://portfolio-efpc.vercel.app/",
    images: [
      {
        url: "https://drive.google.com/uc?id=1Wqlbxgi3hJenBroU9_tEEhw7SXUEpa8p",
        width: 1200,
        height: 630,
        alt: "Portafolio"
      }
    ]
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div> {children} </div>
      </body>
    </html>
  );
}
